spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: baiel123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    jwt:
      secret_key: baielKarybaev123
server:
  port: 8081


